" 记录session
nmap 1s :mksession! ~/.config/nvim/tmp/backup/last_session_1<CR>
nmap 2s :mksession! ~/.config/nvim/tmp/backup/last_session_2<CR>
nmap 3s :mksession! ~/.config/nvim/tmp/backup/last_session_3<CR>
nmap 4s :mksession! ~/.config/nvim/tmp/backup/last_session_4<CR>
nmap 5s :mksession! ~/.config/nvim/tmp/backup/last_session_5<CR>
nmap 6s :mksession! ~/.config/nvim/tmp/backup/last_session_6<CR>
nmap 7s :mksession! ~/.config/nvim/tmp/backup/last_session_7<CR>
nmap 8s :mksession! ~/.config/nvim/tmp/backup/last_session_8<CR>
nmap 9s :mksession! ~/.config/nvim/tmp/backup/last_session_9<CR>
nmap 10s :mksession! ~/.config/nvim/tmp/backup/last_session_10<CR>
nmap 11s :mksession! ~/.config/nvim/tmp/backup/last_session_11<CR>
nmap 12s :mksession! ~/.config/nvim/tmp/backup/last_session_12<CR>
nmap 13s :mksession! ~/.config/nvim/tmp/backup/last_session_13<CR>
nmap 14s :mksession! ~/.config/nvim/tmp/backup/last_session_14<CR>
nmap 15s :mksession! ~/.config/nvim/tmp/backup/last_session_15<CR>
nmap 16s :mksession! ~/.config/nvim/tmp/backup/last_session_16<CR>
nmap 17s :mksession! ~/.config/nvim/tmp/backup/last_session_17<CR>
nmap 18s :mksession! ~/.config/nvim/tmp/backup/last_session_18<CR>
nmap 19s :mksession! ~/.config/nvim/tmp/backup/last_session_19<CR>
nmap 20s :mksession! ~/.config/nvim/tmp/backup/last_session_20<CR>
nmap 21s :mksession! ~/.config/nvim/tmp/backup/last_session_21<CR>
nmap 22s :mksession! ~/.config/nvim/tmp/backup/last_session_22<CR>
nmap 23s :mksession! ~/.config/nvim/tmp/backup/last_session_23<CR>
nmap 24s :mksession! ~/.config/nvim/tmp/backup/last_session_24<CR>
nmap 25s :mksession! ~/.config/nvim/tmp/backup/last_session_25<CR>
nmap 26s :mksession! ~/.config/nvim/tmp/backup/last_session_26<CR>
nmap 27s :mksession! ~/.config/nvim/tmp/backup/last_session_27<CR>
nmap 28s :mksession! ~/.config/nvim/tmp/backup/last_session_28<CR>
nmap 29s :mksession! ~/.config/nvim/tmp/backup/last_session_29<CR>
nmap 30s :mksession! ~/.config/nvim/tmp/backup/last_session_30<CR>
nmap 31s :mksession! ~/.config/nvim/tmp/backup/last_session_31<CR>
nmap 32s :mksession! ~/.config/nvim/tmp/backup/last_session_32<CR>
nmap 33s :mksession! ~/.config/nvim/tmp/backup/last_session_33<CR>
nmap 34s :mksession! ~/.config/nvim/tmp/backup/last_session_34<CR>
nmap 35s :mksession! ~/.config/nvim/tmp/backup/last_session_35<CR>
nmap 36s :mksession! ~/.config/nvim/tmp/backup/last_session_36<CR>
nmap 37s :mksession! ~/.config/nvim/tmp/backup/last_session_37<CR>
nmap 38s :mksession! ~/.config/nvim/tmp/backup/last_session_38<CR>
nmap 39s :mksession! ~/.config/nvim/tmp/backup/last_session_39<CR>
nmap 40s :mksession! ~/.config/nvim/tmp/backup/last_session_40<CR>
nmap 41s :mksession! ~/.config/nvim/tmp/backup/last_session_41<CR>
nmap 42s :mksession! ~/.config/nvim/tmp/backup/last_session_42<CR>
nmap 43s :mksession! ~/.config/nvim/tmp/backup/last_session_43<CR>
nmap 44s :mksession! ~/.config/nvim/tmp/backup/last_session_44<CR>
nmap 45s :mksession! ~/.config/nvim/tmp/backup/last_session_45<CR>
nmap 46s :mksession! ~/.config/nvim/tmp/backup/last_session_46<CR>
nmap 47s :mksession! ~/.config/nvim/tmp/backup/last_session_47<CR>
nmap 48s :mksession! ~/.config/nvim/tmp/backup/last_session_48<CR>
nmap 49s :mksession! ~/.config/nvim/tmp/backup/last_session_49<CR>
nmap 50s :mksession! ~/.config/nvim/tmp/backup/last_session_50<CR>
nmap 51s :mksession! ~/.config/nvim/tmp/backup/last_session_51<CR>
nmap 52s :mksession! ~/.config/nvim/tmp/backup/last_session_52<CR>
nmap 53s :mksession! ~/.config/nvim/tmp/backup/last_session_53<CR>
nmap 54s :mksession! ~/.config/nvim/tmp/backup/last_session_54<CR>
nmap 55s :mksession! ~/.config/nvim/tmp/backup/last_session_55<CR>
nmap 56s :mksession! ~/.config/nvim/tmp/backup/last_session_56<CR>
nmap 57s :mksession! ~/.config/nvim/tmp/backup/last_session_57<CR>
nmap 58s :mksession! ~/.config/nvim/tmp/backup/last_session_58<CR>
nmap 59s :mksession! ~/.config/nvim/tmp/backup/last_session_59<CR>
nmap 60s :mksession! ~/.config/nvim/tmp/backup/last_session_60<CR>
nmap 61s :mksession! ~/.config/nvim/tmp/backup/last_session_61<CR>
nmap 62s :mksession! ~/.config/nvim/tmp/backup/last_session_62<CR>
nmap 63s :mksession! ~/.config/nvim/tmp/backup/last_session_63<CR>
nmap 64s :mksession! ~/.config/nvim/tmp/backup/last_session_64<CR>
nmap 65s :mksession! ~/.config/nvim/tmp/backup/last_session_65<CR>
nmap 66s :mksession! ~/.config/nvim/tmp/backup/last_session_66<CR>
nmap 67s :mksession! ~/.config/nvim/tmp/backup/last_session_67<CR>
nmap 68s :mksession! ~/.config/nvim/tmp/backup/last_session_68<CR>
nmap 69s :mksession! ~/.config/nvim/tmp/backup/last_session_69<CR>
nmap 70s :mksession! ~/.config/nvim/tmp/backup/last_session_70<CR>
nmap 71s :mksession! ~/.config/nvim/tmp/backup/last_session_71<CR>
nmap 72s :mksession! ~/.config/nvim/tmp/backup/last_session_72<CR>
nmap 73s :mksession! ~/.config/nvim/tmp/backup/last_session_73<CR>
nmap 74s :mksession! ~/.config/nvim/tmp/backup/last_session_74<CR>
nmap 75s :mksession! ~/.config/nvim/tmp/backup/last_session_75<CR>
nmap 76s :mksession! ~/.config/nvim/tmp/backup/last_session_76<CR>
nmap 77s :mksession! ~/.config/nvim/tmp/backup/last_session_77<CR>
nmap 78s :mksession! ~/.config/nvim/tmp/backup/last_session_78<CR>
nmap 79s :mksession! ~/.config/nvim/tmp/backup/last_session_79<CR>
nmap 80s :mksession! ~/.config/nvim/tmp/backup/last_session_80<CR>
nmap 81s :mksession! ~/.config/nvim/tmp/backup/last_session_81<CR>
nmap 82s :mksession! ~/.config/nvim/tmp/backup/last_session_82<CR>
nmap 83s :mksession! ~/.config/nvim/tmp/backup/last_session_83<CR>
nmap 84s :mksession! ~/.config/nvim/tmp/backup/last_session_84<CR>
nmap 85s :mksession! ~/.config/nvim/tmp/backup/last_session_85<CR>
nmap 86s :mksession! ~/.config/nvim/tmp/backup/last_session_86<CR>
nmap 87s :mksession! ~/.config/nvim/tmp/backup/last_session_87<CR>
nmap 88s :mksession! ~/.config/nvim/tmp/backup/last_session_88<CR>
nmap 89s :mksession! ~/.config/nvim/tmp/backup/last_session_89<CR>
nmap 90s :mksession! ~/.config/nvim/tmp/backup/last_session_90<CR>
nmap 91s :mksession! ~/.config/nvim/tmp/backup/last_session_91<CR>
nmap 92s :mksession! ~/.config/nvim/tmp/backup/last_session_92<CR>
nmap 93s :mksession! ~/.config/nvim/tmp/backup/last_session_93<CR>
nmap 94s :mksession! ~/.config/nvim/tmp/backup/last_session_94<CR>
nmap 95s :mksession! ~/.config/nvim/tmp/backup/last_session_95<CR>
nmap 96s :mksession! ~/.config/nvim/tmp/backup/last_session_96<CR>
nmap 97s :mksession! ~/.config/nvim/tmp/backup/last_session_97<CR>
nmap 98s :mksession! ~/.config/nvim/tmp/backup/last_session_98<CR>
nmap 99s :mksession! ~/.config/nvim/tmp/backup/last_session_99<CR>
nmap 100s :mksession! ~/.config/nvim/tmp/backup/last_session_100<CR>
nmap 101s :mksession! ~/.config/nvim/tmp/backup/last_session_101<CR>
nmap 102s :mksession! ~/.config/nvim/tmp/backup/last_session_102<CR>





" 读取session
nmap 1r :source ~/.config/nvim/tmp/backup/last_session_1<CR>
nmap 2r :source ~/.config/nvim/tmp/backup/last_session_2<CR>
nmap 3r :source ~/.config/nvim/tmp/backup/last_session_3<CR>
nmap 4r :source ~/.config/nvim/tmp/backup/last_session_4<CR>
nmap 5r :source ~/.config/nvim/tmp/backup/last_session_5<CR>
nmap 6r :source ~/.config/nvim/tmp/backup/last_session_6<CR>
nmap 7r :source ~/.config/nvim/tmp/backup/last_session_7<CR>
nmap 8r :source ~/.config/nvim/tmp/backup/last_session_8<CR>
nmap 9r :source ~/.config/nvim/tmp/backup/last_session_9<CR>
nmap 10r :source ~/.config/nvim/tmp/backup/last_session_10<CR>
nmap 11r :source ~/.config/nvim/tmp/backup/last_session_11<CR>
nmap 12r :source ~/.config/nvim/tmp/backup/last_session_12<CR>
nmap 13r :source ~/.config/nvim/tmp/backup/last_session_13<CR>
nmap 14r :source ~/.config/nvim/tmp/backup/last_session_14<CR>
nmap 15r :source ~/.config/nvim/tmp/backup/last_session_15<CR>
nmap 16r :source ~/.config/nvim/tmp/backup/last_session_16<CR>
nmap 17r :source ~/.config/nvim/tmp/backup/last_session_17<CR>
nmap 18r :source ~/.config/nvim/tmp/backup/last_session_18<CR>
nmap 19r :source ~/.config/nvim/tmp/backup/last_session_19<CR>
nmap 20r :source ~/.config/nvim/tmp/backup/last_session_20<CR>
nmap 21r :source ~/.config/nvim/tmp/backup/last_session_21<CR>
nmap 22r :source ~/.config/nvim/tmp/backup/last_session_22<CR>
nmap 23r :source ~/.config/nvim/tmp/backup/last_session_23<CR>
nmap 24r :source ~/.config/nvim/tmp/backup/last_session_24<CR>
nmap 25r :source ~/.config/nvim/tmp/backup/last_session_25<CR>
nmap 26r :source ~/.config/nvim/tmp/backup/last_session_26<CR>
nmap 27r :source ~/.config/nvim/tmp/backup/last_session_27<CR>
nmap 28r :source ~/.config/nvim/tmp/backup/last_session_28<CR>
nmap 29r :source ~/.config/nvim/tmp/backup/last_session_29<CR>
nmap 30r :source ~/.config/nvim/tmp/backup/last_session_30<CR>
nmap 31r :source ~/.config/nvim/tmp/backup/last_session_31<CR>
nmap 32r :source ~/.config/nvim/tmp/backup/last_session_32<CR>
nmap 33r :source ~/.config/nvim/tmp/backup/last_session_33<CR>
nmap 34r :source ~/.config/nvim/tmp/backup/last_session_34<CR>
nmap 35r :source ~/.config/nvim/tmp/backup/last_session_35<CR>
nmap 36r :source ~/.config/nvim/tmp/backup/last_session_36<CR>
nmap 37r :source ~/.config/nvim/tmp/backup/last_session_37<CR>
nmap 38r :source ~/.config/nvim/tmp/backup/last_session_38<CR>
nmap 39r :source ~/.config/nvim/tmp/backup/last_session_39<CR>
nmap 40r :source ~/.config/nvim/tmp/backup/last_session_40<CR>
nmap 41r :source ~/.config/nvim/tmp/backup/last_session_41<CR>
nmap 42r :source ~/.config/nvim/tmp/backup/last_session_42<CR>
nmap 43r :source ~/.config/nvim/tmp/backup/last_session_43<CR>
nmap 44r :source ~/.config/nvim/tmp/backup/last_session_44<CR>
nmap 45r :source ~/.config/nvim/tmp/backup/last_session_45<CR>
nmap 46r :source ~/.config/nvim/tmp/backup/last_session_46<CR>
nmap 47r :source ~/.config/nvim/tmp/backup/last_session_47<CR>
nmap 48r :source ~/.config/nvim/tmp/backup/last_session_48<CR>
nmap 49r :source ~/.config/nvim/tmp/backup/last_session_49<CR>
nmap 50r :source ~/.config/nvim/tmp/backup/last_session_50<CR>
nmap 51r :source ~/.config/nvim/tmp/backup/last_session_51<CR>
nmap 52r :source ~/.config/nvim/tmp/backup/last_session_52<CR>
nmap 53r :source ~/.config/nvim/tmp/backup/last_session_53<CR>
nmap 54r :source ~/.config/nvim/tmp/backup/last_session_54<CR>
nmap 55r :source ~/.config/nvim/tmp/backup/last_session_55<CR>
nmap 56r :source ~/.config/nvim/tmp/backup/last_session_56<CR>
nmap 57r :source ~/.config/nvim/tmp/backup/last_session_57<CR>
nmap 58r :source ~/.config/nvim/tmp/backup/last_session_58<CR>
nmap 59r :source ~/.config/nvim/tmp/backup/last_session_59<CR>
nmap 60r :source ~/.config/nvim/tmp/backup/last_session_60<CR>
nmap 61r :source ~/.config/nvim/tmp/backup/last_session_61<CR>
nmap 62r :source ~/.config/nvim/tmp/backup/last_session_62<CR>
nmap 63r :source ~/.config/nvim/tmp/backup/last_session_63<CR>
nmap 64r :source ~/.config/nvim/tmp/backup/last_session_64<CR>
nmap 65r :source ~/.config/nvim/tmp/backup/last_session_65<CR>
nmap 66r :source ~/.config/nvim/tmp/backup/last_session_66<CR>
nmap 67r :source ~/.config/nvim/tmp/backup/last_session_67<CR>
nmap 68r :source ~/.config/nvim/tmp/backup/last_session_68<CR>
nmap 69r :source ~/.config/nvim/tmp/backup/last_session_69<CR>
nmap 70r :source ~/.config/nvim/tmp/backup/last_session_70<CR>
nmap 71r :source ~/.config/nvim/tmp/backup/last_session_71<CR>
nmap 72r :source ~/.config/nvim/tmp/backup/last_session_72<CR>
nmap 73r :source ~/.config/nvim/tmp/backup/last_session_73<CR>
nmap 74r :source ~/.config/nvim/tmp/backup/last_session_74<CR>
nmap 75r :source ~/.config/nvim/tmp/backup/last_session_75<CR>
nmap 76r :source ~/.config/nvim/tmp/backup/last_session_76<CR>
nmap 77r :source ~/.config/nvim/tmp/backup/last_session_77<CR>
nmap 78r :source ~/.config/nvim/tmp/backup/last_session_78<CR>
nmap 79r :source ~/.config/nvim/tmp/backup/last_session_79<CR>
nmap 80r :source ~/.config/nvim/tmp/backup/last_session_80<CR>
nmap 81r :source ~/.config/nvim/tmp/backup/last_session_81<CR>
nmap 82r :source ~/.config/nvim/tmp/backup/last_session_82<CR>
nmap 83r :source ~/.config/nvim/tmp/backup/last_session_83<CR>
nmap 84r :source ~/.config/nvim/tmp/backup/last_session_84<CR>
nmap 85r :source ~/.config/nvim/tmp/backup/last_session_85<CR>
nmap 86r :source ~/.config/nvim/tmp/backup/last_session_86<CR>
nmap 87r :source ~/.config/nvim/tmp/backup/last_session_87<CR>
nmap 88r :source ~/.config/nvim/tmp/backup/last_session_88<CR>
nmap 89r :source ~/.config/nvim/tmp/backup/last_session_89<CR>
nmap 90r :source ~/.config/nvim/tmp/backup/last_session_90<CR>
nmap 91r :source ~/.config/nvim/tmp/backup/last_session_91<CR>
nmap 92r :source ~/.config/nvim/tmp/backup/last_session_92<CR>
nmap 93r :source ~/.config/nvim/tmp/backup/last_session_93<CR>
nmap 94r :source ~/.config/nvim/tmp/backup/last_session_94<CR>
nmap 95r :source ~/.config/nvim/tmp/backup/last_session_95<CR>
nmap 96r :source ~/.config/nvim/tmp/backup/last_session_96<CR>
nmap 97r :source ~/.config/nvim/tmp/backup/last_session_97<CR>
nmap 98r :source ~/.config/nvim/tmp/backup/last_session_98<CR>
nmap 99r :source ~/.config/nvim/tmp/backup/last_session_99<CR>
nmap 100r :source ~/.config/nvim/tmp/backup/last_session_100<CR>
nmap 101r :source ~/.config/nvim/tmp/backup/last_session_101<CR>
nmap 102r :source ~/.config/nvim/tmp/backup/last_session_102<CR>


